# Generated by Django 5.2.6 on 2025-09-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='voice_notes/'),
        ),
    ]
