# Generated by Django 5.2.6 on 2025-09-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='content',
            field=models.TextField(blank=True, help_text='Detailed description or context of the task', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='transcript',
            field=models.TextField(blank=True, help_text='AI-generated transcript from audio', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Optional audio file if added via voice', null=True, upload_to='voice_notes/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tasks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Short label for the task, e.g. Studying, Meditating', max_length=200),
        ),
    ]
