# Generated by Django 5.2.6 on 2025-09-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_content_task_transcript_alter_task_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, help_text='Short label for the task, e.g. Studying, Meditating', max_length=200, null=True),
        ),
    ]
