# Generated by Django 5.2.6 on 2025-09-14 08:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='content',
        ),
        migrations.RemoveField(
            model_name='task',
            name='transcript',
        ),
        migrations.AddField(
            model_name='task',
            name='cardColor',
            field=models.CharField(default='4294967295', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='titleColor',
            field=models.CharField(default='4278190080', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='voices/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.CharField(default='00:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='Untitled Task', max_length=255),
        ),
    ]
